services:
  workspace:
    container_name: React_Board_devcon_workspace
    image: mcr.microsoft.com/devcontainers/base:bullseye

    environment:
      TZ: 'Asia/Seoul'

    volumes:
      # Workspace Cache
      - ..:${containerWorkspaceFolder}:cached
    command: sleep infinity